# Generated by Django 6.1.1 on 2026-09-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('recurrence_type', models.CharField(choices=[('interval', 'Interval'), ('fixed', 'Fixed')], max_length=10)),
                ('every_days', models.PositiveIntegerField(blank=True, null=True)),
                ('every_months', models.PositiveIntegerField(blank=True, null=True)),
                ('every_years', models.PositiveIntegerField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True)),
                ('day', models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_done', models.DateField(blank=True, null=True)),
                ('last_note', models.TextField(blank=True, null=True)),
                ('snooze_until', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
